#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
echo "Fetching missing A1 assets from upstream @ a158843b20107949f1a8d7df1b05cd33b9166712..."
mkdir -p "$(dirname "cs336_assignment1_basics.pdf")"
if [[ -f "cs336_assignment1_basics.pdf" ]]; then echo "  skip cs336_assignment1_basics.pdf"; else curl -fsSL -o "cs336_assignment1_basics.pdf" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/cs336_assignment1_basics.pdf"; echo "  ok cs336_assignment1_basics.pdf (965629 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_4d_scaled_dot_product_attention.npz")"
if [[ -f "tests/_snapshots/test_4d_scaled_dot_product_attention.npz" ]]; then echo "  skip tests/_snapshots/test_4d_scaled_dot_product_attention.npz"; else curl -fsSL -o "tests/_snapshots/test_4d_scaled_dot_product_attention.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_4d_scaled_dot_product_attention.npz"; echo "  ok tests/_snapshots/test_4d_scaled_dot_product_attention.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_adamw.npz")"
if [[ -f "tests/_snapshots/test_adamw.npz" ]]; then echo "  skip tests/_snapshots/test_adamw.npz"; else curl -fsSL -o "tests/_snapshots/test_adamw.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_adamw.npz"; echo "  ok tests/_snapshots/test_adamw.npz (288 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_embedding.npz")"
if [[ -f "tests/_snapshots/test_embedding.npz" ]]; then echo "  skip tests/_snapshots/test_embedding.npz"; else curl -fsSL -o "tests/_snapshots/test_embedding.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_embedding.npz"; echo "  ok tests/_snapshots/test_embedding.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_linear.npz")"
if [[ -f "tests/_snapshots/test_linear.npz" ]]; then echo "  skip tests/_snapshots/test_linear.npz"; else curl -fsSL -o "tests/_snapshots/test_linear.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_linear.npz"; echo "  ok tests/_snapshots/test_linear.npz (24840 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_multihead_self_attention.npz")"
if [[ -f "tests/_snapshots/test_multihead_self_attention.npz" ]]; then echo "  skip tests/_snapshots/test_multihead_self_attention.npz"; else curl -fsSL -o "tests/_snapshots/test_multihead_self_attention.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_multihead_self_attention.npz"; echo "  ok tests/_snapshots/test_multihead_self_attention.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_multihead_self_attention_with_rope.npz")"
if [[ -f "tests/_snapshots/test_multihead_self_attention_with_rope.npz" ]]; then echo "  skip tests/_snapshots/test_multihead_self_attention_with_rope.npz"; else curl -fsSL -o "tests/_snapshots/test_multihead_self_attention_with_rope.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_multihead_self_attention_with_rope.npz"; echo "  ok tests/_snapshots/test_multihead_self_attention_with_rope.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_positionwise_feedforward.npz")"
if [[ -f "tests/_snapshots/test_positionwise_feedforward.npz" ]]; then echo "  skip tests/_snapshots/test_positionwise_feedforward.npz"; else curl -fsSL -o "tests/_snapshots/test_positionwise_feedforward.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_positionwise_feedforward.npz"; echo "  ok tests/_snapshots/test_positionwise_feedforward.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_rmsnorm.npz")"
if [[ -f "tests/_snapshots/test_rmsnorm.npz" ]]; then echo "  skip tests/_snapshots/test_rmsnorm.npz"; else curl -fsSL -o "tests/_snapshots/test_rmsnorm.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_rmsnorm.npz"; echo "  ok tests/_snapshots/test_rmsnorm.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_rope.npz")"
if [[ -f "tests/_snapshots/test_rope.npz" ]]; then echo "  skip tests/_snapshots/test_rope.npz"; else curl -fsSL -o "tests/_snapshots/test_rope.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_rope.npz"; echo "  ok tests/_snapshots/test_rope.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_scaled_dot_product_attention.npz")"
if [[ -f "tests/_snapshots/test_scaled_dot_product_attention.npz" ]]; then echo "  skip tests/_snapshots/test_scaled_dot_product_attention.npz"; else curl -fsSL -o "tests/_snapshots/test_scaled_dot_product_attention.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_scaled_dot_product_attention.npz"; echo "  ok tests/_snapshots/test_scaled_dot_product_attention.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_swiglu.npz")"
if [[ -f "tests/_snapshots/test_swiglu.npz" ]]; then echo "  skip tests/_snapshots/test_swiglu.npz"; else curl -fsSL -o "tests/_snapshots/test_swiglu.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_swiglu.npz"; echo "  ok tests/_snapshots/test_swiglu.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_train_bpe_special_tokens.pkl")"
if [[ -f "tests/_snapshots/test_train_bpe_special_tokens.pkl" ]]; then echo "  skip tests/_snapshots/test_train_bpe_special_tokens.pkl"; else curl -fsSL -o "tests/_snapshots/test_train_bpe_special_tokens.pkl" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_train_bpe_special_tokens.pkl"; echo "  ok tests/_snapshots/test_train_bpe_special_tokens.pkl (17801 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_transformer_block.npz")"
if [[ -f "tests/_snapshots/test_transformer_block.npz" ]]; then echo "  skip tests/_snapshots/test_transformer_block.npz"; else curl -fsSL -o "tests/_snapshots/test_transformer_block.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_transformer_block.npz"; echo "  ok tests/_snapshots/test_transformer_block.npz (12552 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_transformer_lm.npz")"
if [[ -f "tests/_snapshots/test_transformer_lm.npz" ]]; then echo "  skip tests/_snapshots/test_transformer_lm.npz"; else curl -fsSL -o "tests/_snapshots/test_transformer_lm.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_transformer_lm.npz"; echo "  ok tests/_snapshots/test_transformer_lm.npz (1920264 bytes)"; fi
mkdir -p "$(dirname "tests/_snapshots/test_transformer_lm_truncated_input.npz")"
if [[ -f "tests/_snapshots/test_transformer_lm_truncated_input.npz" ]]; then echo "  skip tests/_snapshots/test_transformer_lm_truncated_input.npz"; else curl -fsSL -o "tests/_snapshots/test_transformer_lm_truncated_input.npz" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/_snapshots/test_transformer_lm_truncated_input.npz"; echo "  ok tests/_snapshots/test_transformer_lm_truncated_input.npz (960264 bytes)"; fi
mkdir -p "$(dirname "tests/fixtures/gpt2_merges.txt")"
if [[ -f "tests/fixtures/gpt2_merges.txt" ]]; then echo "  skip tests/fixtures/gpt2_merges.txt"; else curl -fsSL -o "tests/fixtures/gpt2_merges.txt" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/fixtures/gpt2_merges.txt"; echo "  ok tests/fixtures/gpt2_merges.txt (456304 bytes)"; fi
mkdir -p "$(dirname "tests/fixtures/gpt2_vocab.json")"
if [[ -f "tests/fixtures/gpt2_vocab.json" ]]; then echo "  skip tests/fixtures/gpt2_vocab.json"; else curl -fsSL -o "tests/fixtures/gpt2_vocab.json" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/fixtures/gpt2_vocab.json"; echo "  ok tests/fixtures/gpt2_vocab.json (1042301 bytes)"; fi
mkdir -p "$(dirname "tests/fixtures/tinystories_sample_5M.txt")"
if [[ -f "tests/fixtures/tinystories_sample_5M.txt" ]]; then echo "  skip tests/fixtures/tinystories_sample_5M.txt"; else curl -fsSL -o "tests/fixtures/tinystories_sample_5M.txt" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/fixtures/tinystories_sample_5M.txt"; echo "  ok tests/fixtures/tinystories_sample_5M.txt (5242880 bytes)"; fi
mkdir -p "$(dirname "tests/fixtures/ts_tests/model.pt")"
if [[ -f "tests/fixtures/ts_tests/model.pt" ]]; then echo "  skip tests/fixtures/ts_tests/model.pt"; else curl -fsSL -o "tests/fixtures/ts_tests/model.pt" "https://raw.githubusercontent.com/stanford-cs336/assignment1-basics/a158843b20107949f1a8d7df1b05cd33b9166712/tests/fixtures/ts_tests/model.pt"; echo "  ok tests/fixtures/ts_tests/model.pt (5623416 bytes)"; fi
echo Done.
